### ISSUE TITLE
Criar template de Pull Request

### ISSUE THREAD

**Issue by LhTaira** [fga-eps-mds/2021-1-PUMA#4]

**Comment by GabrielTiveron** [comment]
Foi criado o template para pull requests, segue abaixo o modelo feito

Fixes #228

## O que faz?

Descreva aqui o que seu Pull Request vai adicionar ao projeto.

## Como validar?

Dê dicas de como o revisor desse PR faz para validar o que foi feito?
(nem sempre é óbvio)

## Problemas conhecidos

Nem sempre seu PR vai estar perfeito e mesmo assim ele pode ser aceito.
Liste alguns pontos de melhora.

* Ainda tem que arrumar aquela coisa
* Isso aqui não deu para fazer

### Issues relacionadas

Closes #nnn

Fixes #nnn

\#nnn
