### ISSUE TITLE
Treinamento de Git

### ISSUE THREAD

**Issue by LhTaira** [fga-eps-mds/2021-1-PUMA#7]
### Data: 23/8 13h - 14h
- Realizadores: Luís, Eduardo e João

Repositório do treinamento: https://github.com/jpmartins201/dojo-git-mds

**Comment by LhTaira** [comment]
# Realização: Dia 1 - 23/8 13h - 14h

### Presença:
- [x] Giulia
- [ ] Nícolas
- [x] Levi
- [x] Artur 

<hr>

**Comment by LhTaira** [comment]
# Realização: Dia 1 - 24/8 13h - 14h

### Presença:
- [ ] Giulia
- [x] Nícolas
- [x] Levi
- [x] Artur 

<hr>

* EPS planejou uma conversa séria sobre compromisso no primeiro momento da reunião
* Eduardo não pôde aparecer com justificativa
* Todos os comparecentes ficaram esperando até 13h25 mas nada foi realizado pois Giulia não apareceu.

**Comment by LhTaira** [comment]
# Realização: Dia 4 - 25/8 13h - 14h

### Presença:
- [x] Giulia
- [ ] Nícolas
- [x] Levi
- [x] Artur 

<hr>

* Nícolas não estava presente e não deu justificativa
* Conversa não foi realizada pois o grupo todo não estava presente
* Giulia não tinha conseguido arrumar seu ambiente e só participou observando
* O treinamento foi começado. Levi fez um commit mas não pôde subir para o remoto porque não tinha sido convidado pro repositório mesmo. Isso aconteceu nos últimos 5 minutos do treinamento então não houve perda.

**Comment by GabrielTiveron** [comment]
# Realização: Dia 6 - 27/8 13h - 14h

### Presença:
- [ ] Giulia
- [ ] Nícolas
- [x] Levi
- [x] Artur 

<hr>

* Giulia e Nícolas não apareceram, sem justificativas
* Todo o treinamento foi realizado com Artur e Levi
